# app.yaml
# The command must reference the Streamlit server settings for Databricks
command: ["streamlit", "run", "app.py", "--server.port", "$DATABRICKS_APP_PORT", "--server.address", "0.0.0.0"]
 
# Set the host environment variable for robustness (optional, but recommended)
env:
  - name: 'STREAMLIT_SERVER_ADDRESS'
    value: '0.0.0.0'
 